// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class Appointment
{
    public int AppointmentId { get; set; }

    public int? CustomerId { get; set; }

    public int? VehicleId { get; set; }

    public int? PackageId { get; set; }

    public DateTime? AppointmentDate { get; set; }

    public string Status { get; set; }

    public int? PromotionId { get; set; }

    public virtual ICollection<AppointmentService> AppointmentServices { get; set; } = new List<AppointmentService>();

    public virtual Customer Customer { get; set; }

    public virtual Order Order { get; set; }

    public virtual ServicePackage Package { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Promotion Promotion { get; set; }

    public virtual ServiceHistory ServiceHistory { get; set; }

    public virtual ICollection<ServiceProgress> ServiceProgresses { get; set; } = new List<ServiceProgress>();

    public virtual Vehicle Vehicle { get; set; }
}