// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class AppointmentService
{
    public int AppointmentId { get; set; }

    public int ServiceId { get; set; }

    public int? Quantity { get; set; }

    public virtual Appointment Appointment { get; set; }

    public virtual Service Service { get; set; }
}