// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class PartPrice
{
    public int PriceId { get; set; }

    public int? PartId { get; set; }

    public decimal Price { get; set; }

    public DateTime? EffectiveFrom { get; set; }

    public virtual Part Part { get; set; }
}