// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class Part
{
    public int PartId { get; set; }

    public string PartName { get; set; }

    public int? Quantity { get; set; }

    public decimal? UnitPrice { get; set; }

    public string Unit { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public int? WarrantyMonths { get; set; }

    public virtual ICollection<PartPrice> PartPrices { get; set; } = new List<PartPrice>();

    public virtual ICollection<ServicePart> ServiceParts { get; set; } = new List<ServicePart>();

    public virtual ICollection<WarrantyClaim> WarrantyClaims { get; set; } = new List<WarrantyClaim>();
}