// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class ServiceHistory
{
    public int ServiceId { get; set; }

    public int? StaffId { get; set; }

    public string Description { get; set; }

    public string Review { get; set; }

    public decimal? LaborHours { get; set; }

    public DateTime? ServiceDate { get; set; }

    public virtual Appointment Service { get; set; }

    public virtual ServiceStaff Staff { get; set; }
}