// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class ServicePart
{
    public int ServiceId { get; set; }

    public int PartId { get; set; }

    public int QuantityRequired { get; set; }

    public virtual Part Part { get; set; }

    public virtual Service Service { get; set; }
}