// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class ServiceProgress
{
    public int ProgressId { get; set; }

    public int? AppointmentId { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Appointment Appointment { get; set; }
}