// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class Vehicle
{
    public int VehicleId { get; set; }

    public int? CustomerId { get; set; }

    public string LicensePlate { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public int? Year { get; set; }

    public int? CarTypeId { get; set; }

    public string Status { get; set; }

    public DateTime? LastService { get; set; }

    public DateTime? NextService { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual CarType CarType { get; set; }

    public virtual Customer Customer { get; set; }
}