// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class WarrantyClaim
{
    public int ClaimId { get; set; }

    public int? PartId { get; set; }

    public int? SupplierId { get; set; }

    public DateOnly? ClaimDate { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public virtual Part Part { get; set; }

    public virtual Supplier Supplier { get; set; }
}